const {chromium}=require('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const assert=require('assert');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const c=await b.newContext({storageState:'artifacts/qa/auth.json',viewport:{width:1440,height:1000}});const p=await c.newPage();p.setDefaultTimeout(60000);const base='http://localhost:3001';const checks=[];async function api(path,method='GET',data){const r=await c.request.fetch(base+path,{method,data});assert(r.ok(),await r.text());return r.json()}
const subjects=(await api('/api/subjects')).subjects;const subject=subjects[0];assert(subject);const now=new Date();const date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const hw=(await api('/api/homework','POST',{subjectId:subject.id,title:'Проверка связей дневника '+Date.now(),description:'Решить задания 1–3',dueDate:date+'T12:00:00'})).homework;
const lesson=(await api('/api/schedule','POST',{subjectId:subject.id,dayOfWeek:now.getDay()||7,startTime:'11:11',endTime:'11:56'})).lesson;
for(const route of ['/','/schedule','/homework','/subjects/'+subject.id]){await p.goto(base+route);await p.locator(`a[href="/homework/${hw.id}"]`).first().waitFor();checks.push('same homework link from '+route)}
await p.goto(base+'/homework/'+hw.id);await p.getByRole('heading',{name:hw.title}).waitFor();await p.getByRole('button',{name:'Готово',exact:true}).click();await p.waitForFunction(()=>document.querySelector('button[aria-pressed="true"]')?.textContent==='Готово');await p.reload();await p.getByRole('button',{name:'Готово',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Готово',exact:true}).getAttribute('aria-pressed'),'true');checks.push('personal status persists');
await api('/api/schedule/exceptions','POST',{date,lessonId:lesson.id,action:'CANCELLED',note:'Проверка отмены'});for(const route of ['/','/schedule']){await p.goto(base+route);await p.getByText(/Проверка отмены/).first().waitFor();checks.push('cancellation reflected in '+route)}
for(const route of ['/members','/class/manage','/subjects/'+subject.id,'/homework/'+hw.id]){await p.setViewportSize({width:390,height:844});await p.goto(base+route);await p.locator('.workspace-content').waitFor();await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('mobile '+route)}
const users=(await api('/api/users')).users;const student=users.find(u=>u.role==='STUDENT');const conv=(await api('/api/conversations','POST',{type:'DIRECT',targetUserId:student.id})).conversation;
const msg=(await api('/api/conversations/'+conv.id+'/messages','POST',{type:'TEXT',content:'Проверка чата '+Date.now()})).message;await api('/api/messages/'+msg.id,'PATCH',{content:'Сообщение изменено QA'});const found=await api('/api/conversations/'+conv.id+'/messages?q='+encodeURIComponent('Сообщение изменено QA'));assert(found.messages.some(m=>m.id===msg.id));checks.push('message edit and search');const forwarded=(await api('/api/messages/'+msg.id,'POST',{action:'forward',conversationId:conv.id})).message;assert(forwarded.isForwarded);await api('/api/conversations/'+conv.id+'/read','POST',{messageId:forwarded.id});await api('/api/messages/'+msg.id,'DELETE');assert(!(await api('/api/conversations/'+conv.id+'/messages')).messages.some(m=>m.id===msg.id));checks.push('forward, read, delete');
await p.goto(base+'/chats?conversation='+conv.id);await p.getByPlaceholder('Напишите сообщение...').waitFor();await p.screenshot({path:'artifacts/qa/chat-mobile-diary.png',fullPage:true});fs.writeFileSync('artifacts/qa/diary-report.json',JSON.stringify({checks},null,2));console.log(JSON.stringify({checks}));}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});


